### ISSUE TITLE
Invalid Address 0xfc761cc8

### ISSUE THREAD

**Issue by Darkaim63** [Zephiles/TTYD-Practice-Codes#1] opened 2019-11-08 06:19 UTC
Game crashes as soon as I open my save.

Edit: Can provide screenshots if needed!

**Comment by Zephiles** [comment] 2019-11-10 04:59
Screenshot(s) of the crash screen would help. Also, make sure you're using the proper gecko code for your version of the game, and make sure that the entire code is present. Also, please state whether you're playing on an emulator or console, and the software and version of the software being used. Very little can be done about this without any further information.

**Comment by Darkaim63** [comment] 2019-11-12 17:55
I got you man! I am currently running Dolphin Emulator v.5.0-11102 with USA version of TTYD. I do have the correct Gecko code cause the Practice Codes worked up until Keelhaul Key then it would crash my game. Provided below is the crash report screenshots. Also I will point out that I am using the TTYD Hard Mode Gecko Code as well as a randomizer along side it.
![G8ME01_2019-11-12_09-55-18](https://user-images.githubusercontent.com/13300875/68696856-971d3980-0532-11ea-896a-e04d36046cb3.png)
![G8ME01_2019-11-12_09-55-25](https://user-images.githubusercontent.com/13300875/68696862-9a182a00-0532-11ea-902d-2abd9438f097.png)

**Comment by Zephiles** [comment] 2019-11-12 20:52
Which randomizer are you using? Because chances are that either the Hard Mode codes, the randomizer, or both are causing issues.

**Comment by Darkaim63** [comment] 2019-11-13 08:33
I used your Randomizer and I'm using Fatguy703's Hard Mode Gecko Code that was included with the tutorial.

**Comment by Zephiles** [comment] 2019-11-13 22:43
I have made several randomizers, so you need to be more specific. One of my randomizers uses a save file like the practice codes does, and another modifies an iso. If you're using the one that modifies an iso, then the hard mode code will cause issues with it.

**Comment by Darkaim63** [comment] 2019-11-15 00:22
Yes it is the Randomizer that patches the ISO

**Comment by Zephiles** [comment] 2019-11-15 00:31
Then it's likely that the hard mode code is overwriting some instructions that the randomizer sets, which is the cause of the crash. Try disabling the hard mode code(s), and then see if it still crashes.

**Comment by Darkaim63** [comment] 2019-11-16 21:17
Thank you my friend, I'll let you know when I get the chance to play again.

**Comment by Zephiles** [comment] 2019-12-13 16:13
Seeing as there hasn't been a response in a long time, and that the issue doesn't seem to be linked to the practice codes at all, I will be closing this issue.

**Closed as completed by Zephiles** 2019-12-13 16:13 UTC
